/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('products').del()
  await knex('products').insert([
    {
      product_id: "521bf727-0cdc-444e-b7d1-ac024172895a", 
      product_name:"align_halter_tank",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "70ed7536-1e7a-4157-b842-657157574ed1", 
      product_name:"focus_halter_tank",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquet lectus proin nibh nisl condimentum. Augue lacus viverra vitae congue eu consequat ac. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Congue nisi vitae suscipit tellus mauris a diam maecenas. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. In pellentesque massa placerat duis ultricies lacus sed turpis. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "e470cb03-22fb-4543-beb8-9d10c7239242", 
      product_name:"running_tank",
      description:"Ante in nibh mauris cursus mattis molestie a. Donec ultrices tincidunt arcu non sodales neque sodales. Et ligula ullamcorper malesuada proin. In pellentesque massa placerat duis ultricies. Mattis enim ut tellus elementum sagittis. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Massa tempor nec feugiat nisl pretium fusce id velit. Volutpat sed cras ornare arcu dui vivamus arcu. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Tellus orci ac auctor augue mauris augue neque gravida in. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Interdum varius sit amet mattis vulputate enim nulla aliquet. Auctor elit sed vulputate mi sit amet. Mattis molestie a iaculis at erat pellentesque. At tellus at urna condimentum mattis pellentesque id nibh. Lectus nulla at volutpat diam ut venenatis tellus in metus.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "4dc4a847-3313-43b0-8659-137564e59d06", 
      product_name:"scooba_tank",
      description:"Ornare lectus sit amet est placerat in egestas erat imperdiet. Ut sem viverra aliquet eget sit amet tellus. Enim diam vulputate ut pharetra sit amet aliquam id diam. Sit amet consectetur adipiscing elit ut aliquam purus. Tortor at risus viverra adipiscing at in. Neque aliquam vestibulum morbi blandit cursus. Eget nunc scelerisque viverra mauris in aliquam sem. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Ultricies tristique nulla aliquet enim. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Velit egestas dui id ornare arcu odio ut sem nulla. Sodales neque sodales ut etiam sit amet nisl purus. Congue quisque egestas diam in. Mattis enim ut tellus elementum sagittis vitae. Mattis rhoncus urna neque viverra justo nec ultrices. Fermentum leo vel orci porta non pulvinar neque laoreet. Ullamcorper dignissim cras tincidunt lobortis. Nunc sed augue lacus viverra vitae congue eu. Lectus urna duis convallis convallis tellus id interdum velit laoreet. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "9f210376-5923-4cb7-a887-398e9d87a197", 
      product_name:"speedy_halter_tank",
      description:"Posuere sollicitudin aliquam ultrices sagittis orci. Quam quisque id diam vel quam elementum pulvinar etiam. Imperdiet nulla malesuada pellentesque elit. Sit amet tellus cras adipiscing. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Porttitor massa id neque aliquam vestibulum morbi blandit. Ultrices mi tempus imperdiet nulla malesuada. Vivamus arcu felis bibendum ut. Montes nascetur ridiculus mus mauris. Amet tellus cras adipiscing enim eu turpis egestas. Ut etiam sit amet nisl purus in mollis nunc sed.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "13b038c5-e9e2-495a-9e18-988242123b89", 
      product_name:"poised_halter_tank",
      description:"Ultrices neque ornare aenean euismod elementum. Phasellus vestibulum lorem sed risus. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Tempor orci dapibus ultrices in iaculis nunc. Vitae semper quis lectus nulla at. Praesent semper feugiat nibh sed pulvinar. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Amet luctus venenatis lectus magna fringilla.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "b1b8461d-abc9-4f2e-a323-d1574e7b55c8", 
      product_name:"bold_muscle_tank",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra nibh cras pulvinar mattis nunc. Nec nam aliquam sem et tortor consequat id. Quis commodo odio aenean sed adipiscing diam donec adipiscing tristique. Semper viverra nam libero justo laoreet sit amet. Pharetra et ultrices neque ornare aenean. At elementum eu facilisis sed. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. At tellus at urna condimentum mattis pellentesque id nibh tortor. Amet luctus venenatis lectus magna. Purus in mollis nunc sed id semper risus in. Pharetra sit amet aliquam id diam maecenas ultricies. Varius morbi enim nunc faucibus.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "9309dd24-af69-4d9c-806c-bcbf4d2200e0", 
      product_name:"mesh_tank",
      description:"Non diam phasellus vestibulum lorem sed risus ultricies tristique. Morbi non arcu risus quis varius quam. Sollicitudin aliquam ultrices sagittis orci a. Est ultricies integer quis auctor elit sed vulputate. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Morbi non arcu risus quis. Ut pharetra sit amet aliquam id diam. Integer eget aliquet nibh praesent. Sodales neque sodales ut etiam sit amet. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Nibh tellus molestie nunc non. Aliquam vestibulum morbi blandit cursus risus at ultrices mi tempus.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "9912b96d-9875-4e6d-8156-02d4c786e8de", 
      product_name:"elevate_tank",
      description:"Nisi quis eleifend quam adipiscing vitae proin sagittis. Quam pellentesque nec nam aliquam. In iaculis nunc sed augue lacus viverra vitae congue. In eu mi bibendum neque. Dictum sit amet justo donec. Risus at ultrices mi tempus. Arcu vitae elementum curabitur vitae nunc sed. Mi bibendum neque egestas congue quisque egestas. In eu mi bibendum neque. Duis convallis convallis tellus id interdum velit laoreet. Augue interdum velit euismod in pellentesque. Quam id leo in vitae turpis massa sed elementum tempus. Enim diam vulputate ut pharetra sit amet.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "5125e412-3600-4daf-9a6f-162290164118", 
      product_name:"sculpt_tank",
      description:"Ut ornare lectus sit amet est. Congue nisi vitae suscipit tellus mauris a diam. Turpis in eu mi bibendum neque egestas congue. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Est velit egestas dui id ornare arcu odio ut sem. Mus mauris vitae ultricies leo. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Rhoncus dolor purus non enim praesent elementum facilisis. Pharetra vel turpis nunc eget. Nibh venenatis cras sed felis. Sed turpis tincidunt id aliquet risus feugiat in ante. Gravida quis blandit turpis cursus in hac. In est ante in nibh mauris cursus mattis molestie a. Vulputate mi sit amet mauris commodo. Massa massa ultricies mi quis hendrerit dolor. Enim ut sem viverra aliquet. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Eleifend mi in nulla posuere sollicitudin aliquam. Orci dapibus ultrices in iaculis nunc.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "f934d06c-5be5-4059-9d61-bada90826058", 
      product_name:"flow_halter_tank",
      description:"Erat nam at lectus urna. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Ac felis donec et odio. Tincidunt augue interdum velit euismod in pellentesque. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Diam phasellus vestibulum lorem sed risus. Ultricies tristique nulla aliquet enim tortor. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Est placerat in egestas erat. Mi sit amet mauris commodo quis imperdiet massa tincidunt. Non diam phasellus vestibulum lorem. Laoreet non curabitur gravida arcu. In pellentesque massa placerat duis ultricies lacus. Semper feugiat nibh sed pulvinar proin gravida. Placerat duis ultricies lacus sed turpis tincidunt id aliquet. Amet consectetur adipiscing elit ut aliquam purus sit amet luctus. Massa tempor nec feugiat nisl pretium. Ipsum faucibus vitae aliquet nec ullamcorper sit.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"tanks",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "79bf28a5-a23b-4aa4-a77d-c7799df554f5", 
      product_name:"train_hoodie",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing diam donec adipiscing tristique risus. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Morbi non arcu risus quis. Semper auctor neque vitae tempus quam pellentesque. Nulla aliquet enim tortor at auctor urna. Egestas dui id ornare arcu. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Aliquet nec ullamcorper sit amet risus nullam eget. Elit eget gravida cum sociis. Est velit egestas dui id ornare arcu odio. Quis vel eros donec ac odio. Vitae suscipit tellus mauris a diam maecenas sed enim. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Tincidunt ornare massa eget egestas purus. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Cursus mattis molestie a iaculis at erat.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "58f709ac-4645-4cf7-ab00-0b23f6d24cb8", 
      product_name:"train_crew_neck",
      description:"Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Ornare aenean euismod elementum nisi quis. Faucibus interdum posuere lorem ipsum. Posuere morbi leo urna molestie at. Arcu non odio euismod lacinia at quis risus sed. Interdum velit euismod in pellentesque massa. Sit amet risus nullam eget felis eget nunc lobortis mattis. Velit egestas dui id ornare arcu odio ut sem nulla. Urna et pharetra pharetra massa massa ultricies mi. Neque laoreet suspendisse interdum consectetur libero. Fames ac turpis egestas sed tempus urna et. Proin fermentum leo vel orci porta non pulvinar.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "2b79254a-98ff-496d-87bb-8e03523abfc0", 
      product_name:"moodie_hoodie",
      description:"Augue mauris augue neque gravida. At urna condimentum mattis pellentesque. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum. In aliquam sem fringilla ut morbi tincidunt. Ultrices in iaculis nunc sed augue. Eget nunc lobortis mattis aliquam. Dictum non consectetur a erat nam at lectus. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Purus sit amet volutpat consequat. Bibendum arcu vitae elementum curabitur vitae. Faucibus nisl tincidunt eget nullam non nisi. Ac auctor augue mauris augue. Viverra tellus in hac habitasse. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Urna et pharetra pharetra massa. Tortor consequat id porta nibh. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Sollicitudin ac orci phasellus egestas tellus rutrum tellus.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "7a7a5d45-3681-4b57-b05f-c51899cd7509", 
      product_name:"her_hoodie",
      description:"Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Cursus eget nunc scelerisque viverra mauris in. Interdum varius sit amet mattis. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Senectus et netus et malesuada fames ac turpis egestas. Lectus sit amet est placerat in egestas erat imperdiet sed. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Lectus arcu bibendum at varius vel pharetra vel turpis. Massa tincidunt dui ut ornare lectus sit amet est. Egestas integer eget aliquet nibh praesent tristique magna sit. Et molestie ac feugiat sed. Facilisis magna etiam tempor orci eu. Facilisis volutpat est velit egestas dui id ornare. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "6b74749a-d8bb-450d-aabd-c06f7fb8380c", 
      product_name:"super_crew_neck",
      description:"Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Id ornare arcu odio ut sem nulla. Velit scelerisque in dictum non consectetur a erat. Odio facilisis mauris sit amet massa vitae tortor condimentum. Elementum tempus egestas sed sed risus pretium quam. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Elementum sagittis vitae et leo duis. Condimentum mattis pellentesque id nibh. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. A lacus vestibulum sed arcu non odio euismod lacinia. Sed velit dignissim sodales ut eu sem integer vitae justo. Vitae et leo duis ut diam quam nulla porttitor massa. Nulla facilisi etiam dignissim diam quis enim lobortis. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Quis risus sed vulputate odio ut. Duis convallis convallis tellus id interdum. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Egestas sed tempus urna et pharetra pharetra. Mattis vulputate enim nulla aliquet porttitor lacus luctus.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "43ac766e-9578-4303-9625-70df01473122", 
      product_name:"the_classic_hoodie",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Nisi porta lorem mollis aliquam ut porttitor leo a diam. Scelerisque viverra mauris in aliquam sem. Urna nunc id cursus metus aliquam eleifend. Amet consectetur adipiscing elit ut. Nam libero justo laoreet sit amet. Sed risus pretium quam vulputate dignissim. Odio tempor orci dapibus ultrices in iaculis nunc sed. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Enim eu turpis egestas pretium aenean pharetra magna ac placerat.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "cb4ae67b-188b-4de9-b89e-f351fae1ada8", 
      product_name:"the_classic_crew_neck",
      description:"Pellentesque habitant morbi tristique senectus et. Neque aliquam vestibulum morbi blandit cursus. Sit amet mauris commodo quis imperdiet. Congue eu consequat ac felis donec. Sed felis eget velit aliquet sagittis id. Magna eget est lorem ipsum dolor sit amet. At imperdiet dui accumsan sit amet nulla facilisi. Tellus mauris a diam maecenas sed enim ut sem viverra. Sed euismod nisi porta lorem mollis aliquam ut. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Elit sed vulputate mi sit amet mauris commodo. Molestie nunc non blandit massa. Pellentesque sit amet porttitor eget dolor morbi non. Iaculis nunc sed augue lacus viverra vitae congue. Eu facilisis sed odio morbi.",
      category_1:"athleisure",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "ccd79be8-8ab2-440b-afbe-4139a07bc797", 
      product_name:"neon_high-rise",
      description:"Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Nisl tincidunt eget nullam non nisi est sit. Sapien et ligula ullamcorper malesuada proin libero. Tempus quam pellentesque nec nam aliquam. Non nisi est sit amet facilisis magna etiam. Fusce id velit ut tortor pretium viverra suspendisse potenti. Rutrum quisque non tellus orci ac auctor. Nam at lectus urna duis convallis convallis tellus id. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Bibendum at varius vel pharetra vel. Mauris nunc congue nisi vitae suscipit tellus mauris. Pulvinar neque laoreet suspendisse interdum consectetur.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "27b127b0-4c0e-490c-9954-467133ae15fa", 
      product_name:"swifty_high-rise",
      description:"Lorem ipsum dolor sit amet consectetur adipiscing elit duis tristique. Vitae ultricies leo integer malesuada nunc vel risus commodo. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Nulla aliquet enim tortor at auctor urna nunc id cursus. Ut ornare lectus sit amet est placerat. Vel pretium lectus quam id leo in vitae. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Ipsum dolor sit amet consectetur adipiscing elit pellentesque. Interdum consectetur libero id faucibus nisl tincidunt eget. Lectus urna duis convallis convallis tellus id interdum velit. Diam in arcu cursus euismod quis viverra nibh cras. Porttitor leo a diam sollicitudin tempor id eu nisl. Neque laoreet suspendisse interdum consectetur libero. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Nunc mi ipsum faucibus vitae. Aliquam ultrices sagittis orci a scelerisque.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "264b398b-c071-4598-bdfd-8a0ea98ecf0d", 
      product_name:"running_high-rise",
      description:"Posuere lorem ipsum dolor sit amet consectetur adipiscing. Urna nec tincidunt praesent semper feugiat nibh. Ac tincidunt vitae semper quis lectus nulla. Feugiat scelerisque varius morbi enim nunc faucibus. Scelerisque fermentum dui faucibus in ornare quam. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Tempus egestas sed sed risus pretium quam vulputate. Sit amet dictum sit amet justo donec enim diam. Rhoncus mattis rhoncus urna neque viverra. Tellus mauris a diam maecenas sed.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "927e3319-8244-49b4-8ea5-322b24bc28c5", 
      product_name:"sweat_v-waist",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa tincidunt. Fringilla phasellus faucibus scelerisque eleifend. Amet commodo nulla facilisi nullam. Elementum integer enim neque volutpat ac tincidunt vitae. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Dui faucibus in ornare quam. Sapien eget mi proin sed. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Pretium vulputate sapien nec sagittis. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Phasellus vestibulum lorem sed risus ultricies tristique nulla. Phasellus egestas tellus rutrum tellus pellentesque eu. Nam libero justo laoreet sit amet cursus. Adipiscing diam donec adipiscing tristique risus. Elit scelerisque mauris pellentesque pulvinar pellentesque. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "2b4810e0-6c06-477b-98f5-425c90814e56", 
      product_name:"train",
      description:"Sit amet dictum sit amet justo donec. Convallis a cras semper auctor. Lorem sed risus ultricies tristique nulla. Nisi porta lorem mollis aliquam ut. Nulla facilisi nullam vehicula ipsum a arcu. Nunc vel risus commodo viverra maecenas. Nisi vitae suscipit tellus mauris a diam. Mollis nunc sed id semper. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Faucibus interdum posuere lorem ipsum dolor sit. Enim praesent elementum facilisis leo. At tellus at urna condimentum mattis pellentesque id nibh.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "61ab7e06-85f1-41c2-bf25-cbea686b0369", 
      product_name:"swifty",
      description:"Sit amet est placerat in egestas erat imperdiet sed. Viverra tellus in hac habitasse. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Elementum eu facilisis sed odio morbi quis commodo odio aenean. In pellentesque massa placerat duis ultricies lacus sed. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Sociis natoque penatibus et magnis dis. Sit amet luctus venenatis lectus magna fringilla urna. Vivamus arcu felis bibendum ut tristique et egestas quis. Orci nulla pellentesque dignissim enim sit amet.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "dffb2c2b-f4db-4f7a-84e2-d9b7dcf9b28d", 
      product_name:"the_one",
      description:"Convallis tellus id interdum velit laoreet id donec ultrices tincidunt. Senectus et netus et malesuada fames ac. Lacus viverra vitae congue eu consequat ac. Arcu non sodales neque sodales ut etiam sit. Convallis convallis tellus id interdum velit laoreet id. Diam quam nulla porttitor massa id neque aliquam. Auctor elit sed vulputate mi sit. Tincidunt id aliquet risus feugiat in. Dolor sed viverra ipsum nunc aliquet bibendum enim. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Et leo duis ut diam quam nulla porttitor. Scelerisque eu ultrices vitae auctor.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "c0c6c537-68e6-4257-a50d-23cfcb1c2b12", 
      product_name:"the_classic",
      description:"Non blandit massa enim nec dui nunc mattis. Nisl tincidunt eget nullam non nisi est. Eget mauris pharetra et ultrices neque ornare aenean. Fusce id velit ut tortor pretium viverra. Eget nunc lobortis mattis aliquam faucibus purus in. Velit egestas dui id ornare arcu odio ut sem nulla. Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Proin sagittis nisl rhoncus mattis rhoncus. Commodo ullamcorper a lacus vestibulum sed arcu. Pellentesque habitant morbi tristique senectus et. Id diam maecenas ultricies mi eget mauris pharetra et ultrices.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "ed881058-5936-496c-ae5c-187759005abc", 
      product_name:"everyday",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere lorem ipsum dolor sit. Mattis pellentesque id nibh tortor id aliquet lectus proin. Adipiscing elit ut aliquam purus sit amet luctus venenatis. Non enim praesent elementum facilisis leo vel fringilla. Blandit volutpat maecenas volutpat blandit aliquam etiam. Sed libero enim sed faucibus turpis in eu mi. Laoreet id donec ultrices tincidunt arcu non sodales neque. Morbi quis commodo odio aenean sed adipiscing diam donec. Quam vulputate dignissim suspendisse in est ante. Blandit aliquam etiam erat velit scelerisque in. Praesent tristique magna sit amet purus gravida quis blandit. Interdum varius sit amet mattis vulputate. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Elit pellentesque habitant morbi tristique senectus et. Velit ut tortor pretium viverra.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "fa21dc55-30fd-482a-948a-9760d969d9d8", 
      product_name:"bulletproof",
      description:"Tincidunt nunc pulvinar sapien et ligula ullamcorper. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Facilisis magna etiam tempor orci eu. Gravida neque convallis a cras. Sit amet cursus sit amet dictum. Turpis tincidunt id aliquet risus. Auctor augue mauris augue neque gravida in fermentum. Consectetur adipiscing elit ut aliquam purus. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Fermentum leo vel orci porta non pulvinar. Tincidunt augue interdum velit euismod in pellentesque massa. Et pharetra pharetra massa massa ultricies mi quis. Arcu dictum varius duis at consectetur lorem donec massa sapien.",
      category_1:"athleisure",
      category_2:"pants",
      category_3:"leggings",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "1b39f8a3-99a3-4ef4-9bec-ed5df1993885", 
      product_name:"the_classic",
      description:"Eu volutpat odio facilisis mauris sit amet massa vitae. Ut sem viverra aliquet eget. Nulla facilisi etiam dignissim diam quis enim. Faucibus interdum posuere lorem ipsum dolor. In ante metus dictum at tempor commodo ullamcorper a. In eu mi bibendum neque egestas congue. Amet mauris commodo quis imperdiet. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Lacus vel facilisis volutpat est velit egestas dui. Urna nec tincidunt praesent semper. Eu feugiat pretium nibh ipsum consequat. Augue eget arcu dictum varius. Morbi tempus iaculis urna id volutpat. Pellentesque id nibh tortor id aliquet lectus proin. In egestas erat imperdiet sed euismod nisi. Molestie a iaculis at erat pellentesque adipiscing commodo. Adipiscing vitae proin sagittis nisl rhoncus mattis. A iaculis at erat pellentesque adipiscing commodo elit at.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "7da6e2a0-097c-4a2f-ba0f-220cebcbbad3", 
      product_name:"the_regal",
      description:"Sem viverra aliquet eget sit amet tellus cras adipiscing. Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Massa sed elementum tempus egestas sed. Neque laoreet suspendisse interdum consectetur libero. Est sit amet facilisis magna etiam. Nec ultrices dui sapien eget mi proin sed libero enim. Id nibh tortor id aliquet lectus. Nibh ipsum consequat nisl vel pretium. Eu consequat ac felis donec et odio pellentesque diam. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Mattis pellentesque id nibh tortor id aliquet. Sit amet porttitor eget dolor morbi non arcu. Purus in mollis nunc sed. Justo eget magna fermentum iaculis eu non. Eget gravida cum sociis natoque. Velit egestas dui id ornare arcu. Tortor posuere ac ut consequat semper viverra nam libero justo. Sed faucibus turpis in eu mi bibendum neque egestas.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "0dde0e40-36f7-471b-8e95-cbf8a4bbc396", 
      product_name:"dolce_sweater",
      description:"Nulla pellentesque dignissim enim sit. Quam lacus suspendisse faucibus interdum posuere lorem. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Laoreet sit amet cursus sit amet. Nam libero justo laoreet sit amet cursus sit amet dictum. Quis blandit turpis cursus in hac habitasse. In hac habitasse platea dictumst quisque sagittis purus sit amet. Habitant morbi tristique senectus et netus et malesuada. Id donec ultrices tincidunt arcu non. Urna neque viverra justo nec ultrices dui. Libero nunc consequat interdum varius sit amet mattis. Felis imperdiet proin fermentum leo vel. Massa tempor nec feugiat nisl pretium fusce id. Placerat orci nulla pellentesque dignissim enim sit amet venenatis. In massa tempor nec feugiat nisl pretium. Posuere urna nec tincidunt praesent. Tristique nulla aliquet enim tortor at auctor urna nunc id. Viverra vitae congue eu consequat ac. Iaculis at erat pellentesque adipiscing commodo elit.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "301bf952-9e1d-49db-9a40-a33023a1ffca", 
      product_name:"the_comfy_sweater",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Urna cursus eget nunc scelerisque viverra mauris. Adipiscing elit ut aliquam purus sit amet. Amet dictum sit amet justo donec enim diam vulputate. Purus sit amet luctus venenatis lectus magna. Urna condimentum mattis pellentesque id nibh tortor. Aenean euismod elementum nisi quis eleifend quam adipiscing. A lacus vestibulum sed arcu non. Mauris cursus mattis molestie a iaculis.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"sweaters",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "7d7d1072-3fd6-475d-83a9-e558ce536c8c", 
      product_name:"sunday_cardigan",
      description:"Sit amet commodo nulla facilisi nullam vehicula ipsum. Donec adipiscing tristique risus nec. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Facilisis gravida neque convallis a cras semper. Nibh tortor id aliquet lectus proin. Mauris nunc congue nisi vitae suscipit tellus mauris a. Est placerat in egestas erat imperdiet sed. Quis vel eros donec ac odio. Nunc faucibus a pellentesque sit amet. Pellentesque id nibh tortor id. Libero volutpat sed cras ornare arcu dui vivamus. Sagittis id consectetur purus ut faucibus pulvinar. Leo a diam sollicitudin tempor id eu. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Sed ullamcorper morbi tincidunt ornare massa eget. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Aenean euismod elementum nisi quis.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"cardigans",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "809a7b1c-2a4b-4ae3-82f7-6025a9b9c3d2", 
      product_name:"knitted_cardigan",
      description:"Ipsum dolor sit amet consectetur adipiscing. At lectus urna duis convallis convallis tellus id. Lorem ipsum dolor sit amet consectetur. Nulla facilisi cras fermentum odio eu. Et odio pellentesque diam volutpat. Proin libero nunc consequat interdum varius. Enim nulla aliquet porttitor lacus luctus. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Pretium lectus quam id leo in vitae. Et malesuada fames ac turpis egestas integer eget aliquet. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Habitasse platea dictumst quisque sagittis purus sit amet. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Semper risus in hendrerit gravida rutrum quisque non tellus. Ac ut consequat semper viverra. Nibh venenatis cras sed felis. Imperdiet proin fermentum leo vel orci. Eget velit aliquet sagittis id.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"cardigans",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "19e0fbd9-f55e-4203-904b-bd2fefe4264d", 
      product_name:"crochet_cardian",
      description:"Quisque egestas diam in arcu cursus euismod quis viverra nibh. Fermentum dui faucibus in ornare quam viverra orci sagittis. Eget nunc lobortis mattis aliquam faucibus purus in massa. Quis varius quam quisque id diam vel quam elementum pulvinar. Odio tempor orci dapibus ultrices in iaculis nunc sed. Tristique senectus et netus et malesuada. Vitae justo eget magna fermentum iaculis. Iaculis at erat pellentesque adipiscing commodo. Suspendisse sed nisi lacus sed viverra. Metus dictum at tempor commodo ullamcorper a lacus. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Varius quam quisque id diam vel. Ipsum consequat nisl vel pretium lectus quam id leo in. Non blandit massa enim nec dui nunc mattis enim ut. Dui vivamus arcu felis bibendum ut. Vitae proin sagittis nisl rhoncus mattis. Dolor sit amet consectetur adipiscing.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"cardigans",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "9b54e231-2ff9-4bed-84a0-fc71a726f748", 
      product_name:"pom_pom_cardigan",
      description:"Semper risus in hendrerit gravida rutrum quisque non tellus. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Sit amet nisl purus in mollis nunc sed id semper. Dolor morbi non arcu risus. Sit amet massa vitae tortor condimentum lacinia quis. Velit egestas dui id ornare arcu. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Habitasse platea dictumst vestibulum rhoncus. Viverra nam libero justo laoreet sit amet. Fusce id velit ut tortor pretium viverra. Amet dictum sit amet justo donec enim diam vulputate ut. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Lacus viverra vitae congue eu consequat ac felis. Id neque aliquam vestibulum morbi. Vitae congue eu consequat ac felis donec. Quisque sagittis purus sit amet. Odio ut enim blandit volutpat.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"cardigans",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "42ad19e6-d757-4900-8b53-4f682d981827", 
      product_name:"oxford_shirt",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam vulputate ut pharetra sit amet. Lorem ipsum dolor sit amet consectetur adipiscing elit. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Ac tincidunt vitae semper quis lectus nulla at. Eget dolor morbi non arcu risus quis varius. Augue ut lectus arcu bibendum at varius vel pharetra. Tincidunt ornare massa eget egestas purus viverra accumsan in. Malesuada bibendum arcu vitae elementum curabitur. Pulvinar elementum integer enim neque volutpat. Viverra suspendisse potenti nullam ac tortor. Volutpat commodo sed egestas egestas fringilla phasellus. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Nisl nisi scelerisque eu ultrices vitae. Purus semper eget duis at tellus. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "264e0e0c-ad1c-4c6a-a079-9c82f07e09d6", 
      product_name:"silk_shirt",
      description:"Velit egestas dui id ornare arcu odio ut sem nulla. Purus gravida quis blandit turpis cursus. Sed odio morbi quis commodo odio aenean sed. Neque aliquam vestibulum morbi blandit cursus risus at. Sed cras ornare arcu dui vivamus arcu felis bibendum ut. Venenatis tellus in metus vulputate eu scelerisque. Purus in massa tempor nec feugiat nisl pretium fusce. Elementum nisi quis eleifend quam adipiscing vitae proin. Sit amet nisl purus in. Molestie nunc non blandit massa enim nec dui nunc. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Tellus cras adipiscing enim eu. Tincidunt tortor aliquam nulla facilisi cras. Donec massa sapien faucibus et molestie ac feugiat sed lectus. Placerat duis ultricies lacus sed turpis tincidunt.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "eeaaca16-0a09-4d3c-aae5-6509ea1d173f", 
      product_name:"popplin_embroidery_shirt",
      description:"Facilisi etiam dignissim diam quis. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Metus dictum at tempor commodo ullamcorper a lacus. Pellentesque sit amet porttitor eget. Faucibus a pellentesque sit amet porttitor eget. Ultricies leo integer malesuada nunc vel risus commodo. Quisque non tellus orci ac auctor augue mauris augue. Dolor sed viverra ipsum nunc aliquet bibendum. Aenean sed adipiscing diam donec. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Massa ultricies mi quis hendrerit dolor. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Sed elementum tempus egestas sed. Eget sit amet tellus cras adipiscing enim. Ut pharetra sit amet aliquam id diam maecenas ultricies mi.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "0cc4292e-3b5b-42d3-8700-588f3cbf56cc", 
      product_name:"relaxed_shirt",
      description:"Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Diam sollicitudin tempor id eu. Tempus urna et pharetra pharetra. Non arcu risus quis varius quam quisque. Quam id leo in vitae turpis massa sed elementum. Sed nisi lacus sed viverra tellus in hac. Eu facilisis sed odio morbi quis commodo odio aenean sed. Sagittis vitae et leo duis ut diam quam nulla. Cras tincidunt lobortis feugiat vivamus at augue eget. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Egestas diam in arcu cursus euismod quis viverra nibh. Ultrices tincidunt arcu non sodales neque sodales. Orci ac auctor augue mauris augue neque gravida in fermentum.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "9ce824d2-5d07-47c2-8f88-de7a936c673a", 
      product_name:"puff_shirt",
      description:"Turpis nunc eget lorem dolor sed. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Venenatis urna cursus eget nunc scelerisque viverra mauris in. Vestibulum lectus mauris ultrices eros in cursus. Est lorem ipsum dolor sit. Orci dapibus ultrices in iaculis nunc sed augue lacus. Semper viverra nam libero justo laoreet sit amet. Commodo ullamcorper a lacus vestibulum sed arcu. Nibh ipsum consequat nisl vel pretium lectus quam id. Id eu nisl nunc mi ipsum faucibus vitae aliquet. Nibh tellus molestie nunc non blandit massa enim nec. Pellentesque dignissim enim sit amet venenatis urna cursus eget nunc. Varius vel pharetra vel turpis nunc. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Sed risus pretium quam vulputate dignissim. Sed odio morbi quis commodo odio aenean sed adipiscing. Curabitur gravida arcu ac tortor dignissim. At quis risus sed vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Fames ac turpis egestas maecenas pharetra convallis.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "b91c2202-2e8a-4f35-902b-c844790074ce", 
      product_name:"croissant_shirt",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit at imperdiet dui accumsan. Hendrerit gravida rutrum quisque non tellus. Mauris cursus mattis molestie a iaculis at erat. Ornare lectus sit amet est placerat in egestas. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Metus vulputate eu scelerisque felis imperdiet. Iaculis nunc sed augue lacus viverra vitae congue. Tristique senectus et netus et malesuada fames ac. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Faucibus turpis in eu mi bibendum neque. Sed libero enim sed faucibus turpis. A erat nam at lectus urna duis convallis convallis. Nec ullamcorper sit amet risus nullam. Tincidunt arcu non sodales neque sodales ut etiam. Bibendum est ultricies integer quis auctor elit sed vulputate.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "52aabda5-872c-4924-96c9-a6cca90fdc52", 
      product_name:"tunic_blouse",
      description:"Nam libero justo laoreet sit amet cursus sit amet dictum. Nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Lacus sed turpis tincidunt id aliquet risus feugiat. Leo vel orci porta non. Ornare arcu odio ut sem nulla. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Dictum at tempor commodo ullamcorper a. Consectetur adipiscing elit ut aliquam purus sit amet. Odio facilisis mauris sit amet. Sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Volutpat lacus laoreet non curabitur gravida arcu ac. Facilisi morbi tempus iaculis urna. Proin gravida hendrerit lectus a. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Amet venenatis urna cursus eget nunc scelerisque viverra.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "e7c2d72a-f09b-4d53-a1a3-d8854e3472ec", 
      product_name:"flowy_blouse",
      description:"Nulla pharetra diam sit amet nisl. Eu augue ut lectus arcu bibendum. Fringilla est ullamcorper eget nulla facilisi etiam. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Diam quam nulla porttitor massa. Dolor purus non enim praesent elementum facilisis leo vel. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Consequat semper viverra nam libero justo. Nisl tincidunt eget nullam non nisi est sit. Massa eget egestas purus viverra accumsan in nisl. Libero nunc consequat interdum varius sit amet mattis vulputate. Amet consectetur adipiscing elit pellentesque habitant morbi. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Egestas sed sed risus pretium. Sit amet purus gravida quis blandit turpis cursus in hac.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "bb1dd67b-8c67-4690-977d-5706f1e36aee", 
      product_name:"drape_blouse",
      description:"Enim nunc faucibus a pellentesque. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Ac auctor augue mauris augue neque gravida. Sit amet dictum sit amet justo. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Imperdiet massa tincidunt nunc pulvinar sapien. Porttitor eget dolor morbi non arcu risus quis varius. Lacus laoreet non curabitur gravida arcu ac tortor. Velit dignissim sodales ut eu sem. Sit amet commodo nulla facilisi nullam. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Vulputate dignissim suspendisse in est. Sed arcu non odio euismod lacinia at quis risus. Convallis tellus id interdum velit laoreet. Id consectetur purus ut faucibus pulvinar elementum. Tincidunt id aliquet risus feugiat in.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "9f90df70-c493-48eb-baaa-e5a754fee38e", 
      product_name:"bustier_top",
      description:"Pharetra massa massa ultricies mi quis hendrerit dolor. Eu augue ut lectus arcu bibendum at varius vel pharetra. Nibh praesent tristique magna sit amet purus gravida quis. Velit sed ullamcorper morbi tincidunt ornare massa. Accumsan tortor posuere ac ut consequat semper viverra. Dui ut ornare lectus sit amet est. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Massa tempor nec feugiat nisl. Id aliquet risus feugiat in ante. Eu facilisis sed odio morbi. Tincidunt eget nullam non nisi est sit amet facilisis. Quis enim lobortis scelerisque fermentum dui faucibus in. Nunc aliquet bibendum enim facilisis. Dictum varius duis at consectetur. Justo eget magna fermentum iaculis eu non. Viverra mauris in aliquam sem fringilla. Sagittis orci a scelerisque purus semper eget. Nunc scelerisque viverra mauris in. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Purus in mollis nunc sed id.",
      category_1:"clothing",
      category_2:"tops",
      category_3:"shirts",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "900c5895-bb77-4a82-8d23-7ec87c359f3e", 
      product_name:"slouch_jeans",
      description:"Leo a diam sollicitudin tempor id eu nisl nunc. Iaculis at erat pellentesque adipiscing commodo elit. Sapien et ligula ullamcorper malesuada. Magna etiam tempor orci eu lobortis elementum nibh tellus. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Gravida neque convallis a cras semper auctor neque vitae tempus. Egestas maecenas pharetra convallis posuere morbi leo urna molestie. Ut aliquam purus sit amet luctus. Tellus molestie nunc non blandit massa enim nec. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Morbi tincidunt augue interdum velit. Ullamcorper a lacus vestibulum sed arcu non odio. Vitae tempus quam pellentesque nec. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet.",
      category_1:"clothing",
      category_2:"pants",
      category_3:"jeans",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "318829c6-e975-47d5-9287-b018632cf900", 
      product_name:"painter_jeans",
      description:"Diam in arcu cursus euismod quis viverra. Varius vel pharetra vel turpis. Ac turpis egestas integer eget. Id porta nibh venenatis cras sed. Leo in vitae turpis massa. Est lorem ipsum dolor sit amet consectetur adipiscing elit. Viverra vitae congue eu consequat ac felis donec et odio. Quis auctor elit sed vulputate mi sit amet. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Est velit egestas dui id ornare arcu odio ut sem.",
      category_1:"clothing",
      category_2:"pants",
      category_3:"jeans",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "d77cfea7-ee1b-4025-b008-7527f40c1a63", 
      product_name:"90's_jeans",
      description:"Consectetur adipiscing elit pellentesque habitant. Velit ut tortor pretium viverra. Mattis molestie a iaculis at erat. Tortor id aliquet lectus proin nibh nisl condimentum. Non nisi est sit amet facilisis magna etiam tempor. Iaculis nunc sed augue lacus viverra vitae congue eu. Nunc consequat interdum varius sit amet mattis. In fermentum et sollicitudin ac. Tempor id eu nisl nunc mi ipsum faucibus vitae. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Ornare arcu odio ut sem nulla pharetra diam sit amet. Ut sem nulla pharetra diam sit amet. Enim lobortis scelerisque fermentum dui.",
      category_1:"clothing",
      category_2:"pants",
      category_3:"jeans",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "4f4a6ba3-6ecd-4c50-a577-f0f33f536bb2", 
      product_name:"classic_jeans",
      description:"Orci nulla pellentesque dignissim enim sit amet venenatis. Nec dui nunc mattis enim ut tellus elementum sagittis. Pellentesque habitant morbi tristique senectus et netus. Odio morbi quis commodo odio aenean sed adipiscing. Sed blandit libero volutpat sed cras ornare arcu dui. Mattis enim ut tellus elementum sagittis vitae et. Nullam eget felis eget nunc lobortis mattis aliquam. In eu mi bibendum neque egestas. Gravida dictum fusce ut placerat orci nulla pellentesque. Enim diam vulputate ut pharetra sit amet aliquam id.",
      category_1:"clothing",
      category_2:"pants",
      category_3:"jeans",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "34f5fd5b-fc71-4746-87d4-01ccc1b9b1d5", 
      product_name:"the_classic",
      description:"Diam quam nulla porttitor massa id. Enim nulla aliquet porttitor lacus luctus. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Adipiscing enim eu turpis egestas. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Diam quam nulla porttitor massa id neque aliquam. Augue mauris augue neque gravida in. Ac placerat vestibulum lectus mauris ultrices. Massa enim nec dui nunc mattis. Netus et malesuada fames ac turpis egestas sed. In nulla posuere sollicitudin aliquam ultrices. Urna et pharetra pharetra massa massa ultricies mi quis hendrerit. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non.",
      category_1:"clothing",
      category_2:"pants",
      category_3:"trousers",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "b388baab-b6aa-4e23-a8ab-0d870373fb16", 
      product_name:"utility_barrel_pant",
      description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eleifend quam adipiscing vitae proin. Netus et malesuada fames ac turpis egestas sed tempus urna. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Integer eget aliquet nibh praesent. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Mauris commodo quis imperdiet massa tincidunt. Proin libero nunc consequat interdum varius sit. Et malesuada fames ac turpis egestas sed tempus. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Pharetra diam sit amet nisl suscipit. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Lacus vel facilisis volutpat est velit egestas dui id ornare.",
      category_1:"clothing",
      category_2:"pants",
      category_3:"trousers",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "47da1091-b5f1-40aa-97dd-3e01e2d24f69", 
      product_name:"taper_pant",
      description:"Lacus luctus accumsan tortor posuere ac. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Leo a diam sollicitudin tempor id. Tortor aliquam nulla facilisi cras fermentum odio. Orci a scelerisque purus semper eget duis at tellus at. Cras sed felis eget velit aliquet. Dolor magna eget est lorem ipsum dolor. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Orci nulla pellentesque dignissim enim. Libero justo laoreet sit amet cursus. Enim lobortis scelerisque fermentum dui faucibus in. Est velit egestas dui id ornare arcu. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Eget mauris pharetra et ultrices neque. At ultrices mi tempus imperdiet nulla malesuada. Vestibulum morbi blandit cursus risus. Convallis tellus id interdum velit.",
      category_1:"clothing",
      category_2:"pants",
      category_3:"trousers",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "8ea43408-0027-4e8c-997f-dde55a463ee3", 
      product_name:"diane",
      description:"Vitae sapien pellentesque habitant morbi. Mauris augue neque gravida in fermentum. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. In fermentum et sollicitudin ac orci phasellus. Consequat nisl vel pretium lectus quam. In pellentesque massa placerat duis ultricies lacus sed. Luctus venenatis lectus magna fringilla urna porttitor. Suspendisse faucibus interdum posuere lorem ipsum dolor. Sed id semper risus in hendrerit gravida rutrum quisque. A iaculis at erat pellentesque adipiscing commodo elit. Varius vel pharetra vel turpis nunc eget lorem. Hendrerit dolor magna eget est. Maecenas sed enim ut sem. Massa massa ultricies mi quis hendrerit. Enim nulla aliquet porttitor lacus luctus. Eu consequat ac felis donec. Posuere morbi leo urna molestie at elementum eu. Gravida in fermentum et sollicitudin. Id cursus metus aliquam eleifend. Tincidunt lobortis feugiat vivamus at augue eget arcu.",
      category_1:"clothing",
      category_2:"pants",
      category_3:"trousers",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "310be15a-22fa-4ede-8278-5e9fd8eae60b", 
      product_name:"woody_dress",
      description:"Pretium viverra suspendisse potenti nullam ac tortor. Enim eu turpis egestas pretium aenean. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Adipiscing commodo elit at imperdiet dui accumsan sit amet. Justo laoreet sit amet cursus sit. Ultricies integer quis auctor elit sed vulputate mi. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. At quis risus sed vulputate odio. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Tincidunt id aliquet risus feugiat in ante metus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Facilisis leo vel fringilla est ullamcorper. In hendrerit gravida rutrum quisque non tellus. Urna duis convallis convallis tellus.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"midi",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "2cb2e428-bc8c-41a9-b1c7-bd7d4fb540d4", 
      product_name:"kelly_dress",
      description:"Netus et malesuada fames ac turpis egestas. Et malesuada fames ac turpis egestas sed tempus urna. Bibendum at varius vel pharetra vel turpis nunc. Sed enim ut sem viverra aliquet eget sit amet. Ut ornare lectus sit amet est placerat. Proin libero nunc consequat interdum varius sit. Nam at lectus urna duis convallis convallis tellus id. Sed lectus vestibulum mattis ullamcorper velit sed. Faucibus scelerisque eleifend donec pretium vulputate sapien. Quis enim lobortis scelerisque fermentum.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"midi",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "2cf37008-f48c-4eda-a18c-5ad13e68b89e", 
      product_name:"the_marilyn",
      description:"Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Nunc non blandit massa enim nec dui. Fermentum et sollicitudin ac orci phasellus. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Bibendum at varius vel pharetra vel turpis. Vel facilisis volutpat est velit egestas dui id ornare arcu. Magna sit amet purus gravida quis blandit turpis cursus in. Nec feugiat nisl pretium fusce id velit ut tortor pretium. A arcu cursus vitae congue. Egestas maecenas pharetra convallis posuere morbi leo urna. Urna neque viverra justo nec ultrices dui sapien eget mi. Non curabitur gravida arcu ac. Metus vulputate eu scelerisque felis imperdiet proin. Amet aliquam id diam maecenas ultricies mi eget mauris pharetra. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Commodo quis imperdiet massa tincidunt nunc pulvinar. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Cursus turpis massa tincidunt dui ut ornare.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"midi",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "d8c09e3d-92a3-4bb5-bd89-7281de4c9798", 
      product_name:"the_audrey",
      description:"Vitae tortor condimentum lacinia quis vel eros. Viverra nam libero justo laoreet sit. Scelerisque felis imperdiet proin fermentum. Gravida rutrum quisque non tellus. Tellus id interdum velit laoreet. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Vel risus commodo viverra maecenas accumsan. In dictum non consectetur a. Non blandit massa enim nec dui nunc. Ipsum consequat nisl vel pretium. Nunc aliquet bibendum enim facilisis gravida neque convallis a. Risus feugiat in ante metus dictum at. Ultricies mi eget mauris pharetra. Sed odio morbi quis commodo odio aenean sed. Tristique nulla aliquet enim tortor at auctor urna. Ipsum dolor sit amet consectetur adipiscing.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"midi",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "bbe622d3-3e09-4c7c-a85d-216eeb613634", 
      product_name:"charmeuse_gown",
      description:"Dictum at tempor commodo ullamcorper. Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Libero enim sed faucibus turpis in. Dui faucibus in ornare quam viverra. Urna et pharetra pharetra massa massa ultricies. Tincidunt tortor aliquam nulla facilisi cras. Sed tempus urna et pharetra. Feugiat vivamus at augue eget arcu dictum varius duis. Sed id semper risus in. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Risus sed vulputate odio ut enim blandit volutpat maecenas. At auctor urna nunc id cursus. At tempor commodo ullamcorper a lacus vestibulum sed. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Vitae semper quis lectus nulla at volutpat. Sed blandit libero volutpat sed cras ornare arcu. Eleifend mi in nulla posuere. Sit amet mattis vulputate enim nulla. Id consectetur purus ut faucibus pulvinar elementum integer enim neque.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"maxi",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "624f51af-f87f-458c-910c-a44efcd1273b", 
      product_name:"halter_neck_dress",
      description:"Molestie ac feugiat sed lectus. Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. Sapien eget mi proin sed libero. Eget nunc scelerisque viverra mauris. Fermentum leo vel orci porta. Massa vitae tortor condimentum lacinia quis. Ac tortor vitae purus faucibus ornare. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Nisi quis eleifend quam adipiscing vitae proin. Sit amet nulla facilisi morbi tempus iaculis urna.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"maxi",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "f942f189-3635-4848-809d-f20ab955e5b4", 
      product_name:"silk_kimono_dress",
      description:"Facilisi nullam vehicula ipsum a arcu cursus. Adipiscing elit pellentesque habitant morbi tristique. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Risus nec feugiat in fermentum posuere. Ut etiam sit amet nisl purus. Tellus id interdum velit laoreet. Fames ac turpis egestas integer eget aliquet nibh praesent. Placerat in egestas erat imperdiet sed euismod nisi porta. Vivamus arcu felis bibendum ut. Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Gravida rutrum quisque non tellus orci ac auctor augue. Eget egestas purus viverra accumsan in. Sapien eget mi proin sed libero. Id aliquet lectus proin nibh nisl condimentum id. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Leo vel fringilla est ullamcorper eget. Quam lacus suspendisse faucibus interdum posuere lorem. Sit amet justo donec enim diam vulputate ut pharetra. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"maxi",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "1e6ff504-82f1-463e-9ba9-af090621beab", 
      product_name:"linen_jumpsuit",
      description:"Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Id ornare arcu odio ut sem nulla pharetra diam. Odio euismod lacinia at quis risus sed vulputate odio. Mauris in aliquam sem fringilla ut morbi. Dui ut ornare lectus sit amet est. Dui sapien eget mi proin sed libero. Habitant morbi tristique senectus et netus et. Ipsum a arcu cursus vitae congue. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. Turpis egestas integer eget aliquet nibh praesent tristique magna.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"jumpsuit",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "ea6404c1-c925-4aaa-9912-63e8406d66dc", 
      product_name:"paige",
      description:"In tellus integer feugiat scelerisque. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Commodo elit at imperdiet dui accumsan sit amet. Feugiat sed lectus vestibulum mattis ullamcorper. Lorem donec massa sapien faucibus et. Sed id semper risus in hendrerit gravida rutrum quisque non. Odio facilisis mauris sit amet massa. Diam maecenas sed enim ut sem viverra. Egestas integer eget aliquet nibh praesent tristique.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"jumpsuit",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "515ba6d1-aac1-4c77-88d5-dab5b2841f47", 
      product_name:"yvonne",
      description:"Nibh praesent tristique magna sit amet. A diam maecenas sed enim ut sem viverra aliquet. Et tortor at risus viverra adipiscing at in. Ut aliquam purus sit amet luctus venenatis lectus magna. Varius quam quisque id diam vel quam elementum. Tincidunt eget nullam non nisi. Urna nunc id cursus metus. Vulputate enim nulla aliquet porttitor. Quis eleifend quam adipiscing vitae proin. At erat pellentesque adipiscing commodo. Amet cursus sit amet dictum. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Neque gravida in fermentum et sollicitudin ac orci phasellus. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Neque aliquam vestibulum morbi blandit cursus risus. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Velit egestas dui id ornare. Etiam sit amet nisl purus.",
      category_1:"clothing",
      category_2:"dresses_jumpsuits",
      category_3:"jumpsuit",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "ae4fca74-650a-4232-a4b7-206e803ab0eb", 
      product_name:"puffy_shoulder_bag",
      description:"Curabitur vitae nunc sed velit dignissim sodales ut eu. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Ut faucibus pulvinar elementum integer enim neque. Odio ut enim blandit volutpat maecenas volutpat blandit. Iaculis nunc sed augue lacus viverra vitae congue eu. Bibendum arcu vitae elementum curabitur vitae nunc. Nam at lectus urna duis convallis convallis. Vitae tortor condimentum lacinia quis vel. Rhoncus est pellentesque elit ullamcorper dignissim cras. Et egestas quis ipsum suspendisse ultrices gravida.",
      category_1:"bags",
      category_2:"handbags",
      category_3:"shoulder",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "99b60155-9ced-45d9-a6b4-aa3b4a5d25f6", 
      product_name:"leather_weave_shoulder_bag",
      description:"Sed euismod nisi porta lorem mollis aliquam ut porttitor leo. Aliquam faucibus purus in massa tempor nec feugiat nisl. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Etiam tempor orci eu lobortis elementum. Mauris vitae ultricies leo integer malesuada nunc. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Justo donec enim diam vulputate ut pharetra sit amet aliquam. Morbi blandit cursus risus at. Proin sed libero enim sed faucibus turpis in eu mi. Lobortis elementum nibh tellus molestie.",
      category_1:"bags",
      category_2:"handbags",
      category_3:"shoulder",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "7ad8cbe9-8c68-42e2-b643-b03367ccfe72", 
      product_name:"penelope",
      description:"Convallis aenean et tortor at risus. Ut sem nulla pharetra diam sit amet nisl. At in tellus integer feugiat scelerisque. Tellus elementum sagittis vitae et leo duis. Amet justo donec enim diam vulputate ut pharetra. Hac habitasse platea dictumst quisque. Morbi tincidunt ornare massa eget. Nec feugiat nisl pretium fusce id velit ut. Non nisi est sit amet facilisis magna etiam tempor orci. Leo a diam sollicitudin tempor id eu. Gravida arcu ac tortor dignissim convallis aenean et. Nulla at volutpat diam ut venenatis.",
      category_1:"bags",
      category_2:"handbags",
      category_3:"top_handle_satchel",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "10f24688-8794-4dd2-bc29-5617e24a4c30", 
      product_name:"penne",
      description:"Maecenas accumsan lacus vel facilisis volutpat est. Commodo sed egestas egestas fringilla. Lacus sed turpis tincidunt id aliquet risus. Quam lacus suspendisse faucibus interdum. Sit amet justo donec enim. Adipiscing enim eu turpis egestas. Elementum integer enim neque volutpat ac tincidunt. Quam quisque id diam vel quam. Donec ac odio tempor orci. Eget nunc lobortis mattis aliquam faucibus. Aliquet enim tortor at auctor urna. Enim ut tellus elementum sagittis vitae. Condimentum mattis pellentesque id nibh tortor id. Tristique sollicitudin nibh sit amet commodo nulla. Nunc sed velit dignissim sodales ut eu sem. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Sit amet dictum sit amet justo. Porttitor massa id neque aliquam.",
      category_1:"bags",
      category_2:"handbags",
      category_3:"top_handle_satchel",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "fdc2c7aa-3c2e-4858-a14e-804ae66ffe7f", 
      product_name:"siobhan",
      description:"",
      category_1:"bags",
      category_2:"handbags",
      category_3:"top_handle_satchel",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "2af92212-97ad-43fc-b7df-46e22d638c81", 
      product_name:"sling_tote",
      description:"Erat velit scelerisque in dictum. Et pharetra pharetra massa massa ultricies mi quis hendrerit. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Bibendum est ultricies integer quis auctor elit sed. Duis tristique sollicitudin nibh sit amet. Pretium vulputate sapien nec sagittis aliquam. Nulla at volutpat diam ut venenatis. Semper feugiat nibh sed pulvinar proin gravida. Id donec ultrices tincidunt arcu non. Mauris vitae ultricies leo integer malesuada nunc vel risus. Semper feugiat nibh sed pulvinar proin. Quis auctor elit sed vulputate mi sit amet mauris commodo. Maecenas ultricies mi eget mauris pharetra et.",
      category_1:"bags",
      category_2:"handbags",
      category_3:"tote",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
    {
      product_id: "25313e7f-1da2-49c4-ad2a-f50de05d8a77", 
      product_name:"daily_tote",
      description:"Fermentum dui faucibus in ornare quam viverra. Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Quis blandit turpis cursus in hac. Quis varius quam quisque id diam vel quam elementum. Parturient montes nascetur ridiculus mus. Eu lobortis elementum nibh tellus molestie nunc. Lacus vel facilisis volutpat est velit egestas dui id ornare. Et tortor consequat id porta nibh. Id ornare arcu odio ut sem nulla. Eget gravida cum sociis natoque. Posuere morbi leo urna molestie at elementum eu facilisis sed. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Massa id neque aliquam vestibulum. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor. Tellus id interdum velit laoreet. Sed elementum tempus egestas sed sed risus pretium quam. Faucibus in ornare quam viverra orci sagittis. Commodo elit at imperdiet dui accumsan sit amet. Curabitur vitae nunc sed velit dignissim sodales ut eu sem.",
      category_1:"bags",
      category_2:"handbags",
      category_3:"tote",
      status:"active",
      created_on:"2023-08-01 00:00:00",
      updated_on:"2023-08-01 00:00:00",
    },
  ]);
};
